### ISSUE TITLE
Isolation of components inside the iframe

### ISSUE THREAD

**Issue by zvictor** [kadirahq/react-storybook#131]
I am having a hard time with the isolation of components inside the storybook's iframe.
The elements **absolute positioned** are not using the iframe's viewport as anchor. 
Stating `position: relative` to `#root` solved it, but I could not understand why.

![slice 1](https://cloud.githubusercontent.com/assets/181076/14709460/ffbe97da-07d0-11e6-823e-893de9ba910b.png)

**Comment by arunoda** [comment]
Hmm. I have no idea why is that?
Let me know anyone finds something about this.

**Comment by lowkay** [comment]
@zvictor I just tried this out with an absolutely positioned element and it anchored to the iframe fine. Can you give more details about the component style you have applied to your custom component, what version of Chrome you're running etc.?

@arunoda I think that the ml-root component should have height: 100% and position: relative set so that it acts as the 'stage' in a well-defined way for absolutely positioned children.

**Comment by lowkay** [comment]
Actually, I suppose you could say as react-storybook doesn't care what you're rendering it's up to you to style the preview as required. i.e. define preview.css that sets up the html/body/root elements how you want it and require it from your .storybook/config.js. After all if you have your own component css you're loading if react-storybook defined styles they would blat your css.

**Comment by arunoda** [comment]
@lowkay you are correct. We don't (and won't) do anything for the root div inside the iframe(preview). It's something the app should take care. May be a custom CSS and something within the app should handle that.

I want to get the default browser settings inside the iframe.

**Comment by zvictor** [comment]
I couldn't reproduce this anymore, therefore I am closing it for now. Thank you guys for taking a look at it.
