### ISSUE TITLE
Integrate React-Hot-Loader?

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/react-storybook#207]
Is this possible to integrate? http://gaearon.github.io/react-hot-loader/

**Comment by arunoda** [comment]
@kevinSuttle could you tell me why? There is no reason on doing that.
We are directly hook into Webpack's HMR API and work with it.
Since we are managing the state, there's no need of special tooling for React.

**Comment by kevinSuttle** [comment]
Ah ok that makes sense.

**Comment by KevinGhadyani-minted** [comment]
This is incorrect. Because Storybook doesn't retain React component state when reloading stories. This makes hot-reloading pretty useless. One of the most-powerful features of hot-reloading is its ability to retain component state so you could, for instance, bring up a modal and work on its code while it remains open.

Once saving a file causes the modal to disappear (because component state is reset), HMR loses most of its advantage over live reloading (refreshing the entire page or iframe).
