### ISSUE TITLE
How to disable mangled component names during build-storybook

### ISSUE THREAD

**Issue by stipsan** [kadirahq/react-storybook#363]
Hey,

When you build a static storybook the component names get mangled, as seen here: http://uikit-react.io/

This is suboptimal when using the [React Storybook Info Addon](https://github.com/kadirahq/react-storybook-addon-info)
I've tried to use the "full-control" mode but without luck. 

Here's the webpack config for the storybook: https://github.com/stipsan/uikit-react/blob/master/.storybook/webpack.config.js

**Comment by mnmtanish** [comment]
It's happening because component names are getting minified. It's done by the uglifyjs plugin [here](https://github.com/kadirahq/react-storybook/blob/master/src/server/config/webpack.config.prod.js#L27). You can remove that plugin with the "ful-control" mode to fix the issue. A better solution is to set the `displayName` property for your React Components so it'll work with the info addon and React Devtools.

**Comment by arunoda** [comment]
I think thanish has the answer. Check the storybook-addon repo's issues for more info on this.

**Comment by stipsan** [comment]
Hey guys,

While the displayName solution works in most cases, it appears it does not work for components passed as props.

Example: https://form.uikit-react.io/?selectedKind=renderInput&selectedStory=Basic%20Usage&full=0&down=1&left=1&panelRight=0

Here it should be:
```
<Field
    component={renderField}
```

But instead it's:
```
<Field
    component={c()}
```

Despite giving it `displayName` [here](https://github.com/stipsan/redux-form-uikit/blob/master/src/stories/renderInput.js#L8).

Is it possible to override the mangle without having to use `full-control` mode? With Webpack 2 closing in, having to do full-control mode will likely have to be redone then.

Thanks
