### ISSUE TITLE
Don't need storybook-deployer to gh-pages anymore

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#386]
https://github.com/blog/2228-simpler-github-pages-publishing

Simply build them in docs folder and make the appropriate settings for the repository.

**Comment by arunoda** [comment]
Yeah. We can set a prepublish script or something like that to generate the storybook and put it into the docs directory.

**Comment by arunoda** [comment]
I'll put this into the next version of documentation.

**Comment by travi** [comment]
since this would mean versioning that auto-generated docs/ folder, i personally would not prefer that change. i actually prefer to have a CI job run to do this automatically rather than dealing with the noise of generated files in git.

just throwing this on the table as a reminder that some prefer the current approach in case something is done to change in this direction. please at least keep the current approach as an option

**Comment by arunoda** [comment]
Yep. We are not going to kill this :)
