### ISSUE TITLE
Environment variables are not working

### ISSUE THREAD

**Issue by madushan1000** [kadirahq/react-storybook#495]
`process.env.<VAR>` type statements are not working in both the storybook static version and the dev server. Storybook version is 2.19.0.

**Comment by arunoda** [comment]
I think this is working properly.
We need to use `process.env.STORYBOOK_XXX` in our source code.
We can't get all these values via `process.env`.

That's because webpack simply's define plugin simply replace a give key which is like C preprocessor.

But, we should provide a way to get it via `process.env` to avoid the confusion.

**Comment by mnmtanish** [comment]
There's also an `EnvironmentPlugin` which comes bundled with webpack
https://github.com/webpack/docs/wiki/list-of-plugins#environmentplugin

**Comment by arunoda** [comment]
Does it provide `process.env`?

**Comment by arunoda** [comment]
Anyway, we can close this.

**Comment by ilyakatz** [comment]
> We can't get all these values via process.env.

Why is this the case? Is there another way for the stories code to access environmental variables?

**Comment by dzotos** [comment]
@mnmtanish worked for me. thanks!
