### ISSUE TITLE
Hostname for storybook not localhost anymore

### ISSUE THREAD

**Issue by joscha** [kadirahq/react-storybook#502]
We just upgraded to 2.20.0 and see some problems with Storybook starting under a different hostname. Before it was always `localhost` now it seems to be the machine name. Even when `-h 0.0.0.0` or `-h localhost` is passed. I am still investigating why this is happening with the new version.

**Comment by mnmtanish** [comment]
Hi @joscha, thanks for reporting this. It's a bug recently crept into Storybooks, I'm working on the fix right now.

**Comment by mnmtanish** [comment]
Released `v2.20.1` with a patch. It should work correctly now.

This happened when I mistakenly removed the `STORYBOOK_` prefix from config environment variables (because the same prefix is used to send data to the client). [[source]](https://github.com/kadirahq/react-storybook/pull/481/files#diff-6e0d62f54b853b53af874f5965d7adf2R31)

**Comment by joscha** [comment]
nice one, thank you @mnmtanish

**Comment by joscha** [comment]
just verified: this fixed the problem!
