### ISSUE TITLE
Add a simple routing/url system

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#6]
Otherwise, after a manual reload we can't get the same story.

**Comment by lowkay** [comment]
Howdy,

I've been having a poke around the code and got a working implementation of this feature using react-router.

To get it to work nicely I did a bit of refactoring. I wasn't really initially intending on opening a PR so I changed more than just implementing the feature - such as renaming files to have a jsx extension and naming them CamelCase if they export a type rather than a module.

Anyhow, I plan on raising a PR in the next couple of days and we can discuss the changes. There may be choices that you don't agree with and I'm obviously open to changing things to fit in with the project style/outlook.

Just putting it out there in case somebody else is thinking about this feature.

**Comment by arunoda** [comment]
I was also going to re-factor the UI code a bit using the [Mantra](https://github.com/kadirahq/mantra) architecture. But, feel free to send the PR directly.

**Comment by arunoda** [comment]
Now this is implemented in the latest release: `v1.20.0`

**Comment by arunoda** [comment]
If someone looking for how to use React Router `<Links>` in Storybook, check this: https://github.com/kadirahq/react-storybook/issues/485#issuecomment-249401443
