### ISSUE TITLE
Failure parsing .babelrc with comments

### ISSUE THREAD

**Issue by namuol** [kadirahq/react-storybook#95]
Comments can apparently be used in `.babelrc` files, [as is done in **react-redux-starter-kit**](https://github.com/davezuko/react-redux-starter-kit/blob/844e966688910ac79aed4629da0edfd4d7794fff/.babelrc), like so:

```js
// foo bar biz baz
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": ["transform-runtime"]
}
```

Storybook parses `.babelrc` configuration somewhere and fails when it encounters `//`. 
It's easy to work-around (remove the comments):

```
start-storybook -p 9001

=> Using custom .babelrc configurations.
=> Error parsing .babelrc file: Unexpected token /
```

However, Babel allows comments in its config, so Storybook should probably expect to encounter them, right?

**Comment by arunoda** [comment]
yes. We should use [cjson parser](https://www.npmjs.com/package/cjson) I guess.

This is the place we should do it. See: https://github.com/kadirahq/react-storybook/blob/master/src/server/config.js#L18

I am open to PRs for this.

**Comment by STRML** [comment]
Just a note on this - since this shows up in Google - babel [uses json5](https://github.com/babel/babel/blob/dc1f40540de11045bb4714350350e012fee4f93e/packages/babel-core/src/transformation/file/options/option-manager.js#L9) rather than cjson.

[json5](http://json5.org/) is a little more liberal and supports unquoted keys, single quotes, trailing commas, etc. So if you're using cjson you may still have issues with valid babelrc files.
